[package]
name = "trusted"
version = "0.1.0"
authors = ["Dmitry Gritsay <dmitry@vinted.com>"]

[lib]
crate-type = ["dylib"]

[dependencies]
hyper = "0.9.10"
lazy_static = "0.2.1"
ruru = { path = "/Users/dmitry/sites/rust/ruru" }
